### PR TITLE
Refactored to allow Encryption keys to be supplied In-Memory #65

### PR DESCRIPTION
**Pull request by martinjt**
This is the first part, getting the ClearSign, Encrypted, etc. using a new interface.

I toyed with the idea of an abstract class, but my feeling is that there will be another method as part of this next phase for getting the right keys when multiple are supplied, so it felt better as an interface.  This also allows implementors to add in things like storing the keys in a database easier.

The only advantage I could see for an abstract class was the having some private helpers, but that seemed like a stretch.

### CODE REVIEW

**Comment by martinjt** [comment]
I haven't added any additional unit tests in here as I believe that all new methods are covered by existing tests.  The exception would be the hitting of the exclusions.

**Comment by mattosaurus** [comment]
Hi, thanks for submitting this PR, I'm on holiday at the moment but will have a look over this when I'm back next week.

I know @bitcoinbrisbane was looking at refactoring to use an interface as well for #64 so I'll see if I can combine the two if possible.

**Comment by bitcoinbrisbane** [comment]
> Hi, thanks for submitting this PR, I'm on holiday at the moment but will have a look over this when I'm back next week.
> 
> I know @bitcoinbrisbane was looking at refactoring to use an interface as well for #64 so I'll see if I can combine the two if possible.

Might get time to look at this tomorrow 26/8/2020

**Comment by bitcoinbrisbane** [comment]
> This is the first part, getting the ClearSign, Encrypted, etc. using a new interface.
> 
> I toyed with the idea of an abstract class, but my feeling is that there will be another method as part of this next phase for getting the right keys when multiple are supplied, so it felt better as an interface. This also allows implementors to add in things like storing the keys in a database easier.
> 
> The only advantage I could see for an abstract class was the having some private helpers, but that seemed like a stretch.

Looks good, and doesn't effect my interfaces.

**Comment by martinjt** [comment]
I've added the Decrypt part as another commit.

**Review by bitcoinbrisbane — APPROVED** [review]
Looks good to me.

**Comment by mattosaurus** [comment]
I've just merged these into the development branch where I'll take a look over them and then merge into the master if all looks good.

Thanks for making these changes.

**Comment by mattosaurus** [comment]
In the EncryptionKeys class would it make sense to have PublicKey get the first key from PublicKeys rather than storing it seperatly?

Something like this maybe.

```
public PgpPublicKey PublicKey
{
	get
	{
		return PublicKeys.FirstOrDefault();
	}
}
```

I don't think it would make any practical difference but it would mean we don't have 2 different stores of public keys.

**Comment by mattosaurus** [comment]
It would also be nice to be able to refer to keys by their creators name as in gpg.

`gpg --encrypt --sign --recipient 'some user ID value' "C:\TEMP\keys\content.txt"`

Maybe we could add something like `PgpPublicKey FindPublicKey(string userName);` to IEncryptionKeys, though I'm not sure how easy this would be to implement. I'll have a think about this but it could always be added at a latter date if we thought it would be useful but don't want to do it now.

**Comment by martinjt** [comment]
The idea was to keep it simple as a first pass, so although I would agree those may make sense, I'm not sure they should be part of the first pass.

I'm actually not sure what benefit you get from pushing that onto the implementer of the interface.  To me that sound more like a helper function  as it would be common, and not vary by implementation.  That is, if there was an implementation that got keys from a DB, would that actually provide any different way to get those keys?

**Comment by mattosaurus** [comment]
Yeah, probably best to keep it simple initially.

I thought it might fit on the implementor given we have the FindSecretKey method there but am happy to leave it as is and then maybe add in as a utility method later on.

**Comment by mattosaurus** [comment]
With the EncryptionKeys, I'd envisioned that we'd be supplying it in the PGP constructor like so.

```
public PGP(IEncryptionKeys encryptionKeys)
{
	EncryptionKeys = encryptionKeys;
}
```

And that this PGP.EncryptionKeys property would then be the key source for all methods rather than having to supply an EncryptionKeys parameter for each method.

This would however mean that the same PGP instance couldn't be used for encrypting different files with different keys, though maybe this is a good thing to help enforce a logical seperation between clients.

```
PGP client1Pgp = new PGP(client1EncryptionKeys);
PGP client2Pgp = new PGP(client2EncryptionKeys);
```

Do you think this would work or not and do you think it would work in addition to providing the encryption keys to the method as you've done or if having both options would lead to confusion?

**Comment by martinjt** [comment]
I thought the same thing about the constructor.  It does seem like the right place to put it, but again, it didn't feel like the right time to make that kind of change to the composition.

Doing it that way would allow for easier dependency injection, which is why I thought it would be good.

However, doing that, I'd expect to remove all the keys from all the methods.  So it's probably best as a V2 version.

**Comment by mattosaurus** [comment]
Yeah, part of my thinking behind wanting to refactor this was to have it work nicely with dependency injection.

I'm happy to leave this for a v2 version, we can then update the readme examples and maybe depreciate the old methods, but given how much of a breaking change this would be we probably wouldn't want to remove keys from the methods for a long time.

**Comment by martinjt** [comment]
Removing them as part of a larger interface refactor as part of a V2 would be fine.  Major versions, major changes.

I may give it a go as a new branch in the next few weeks and see what it looks like.

**Comment by martinjt** [comment]
Hey, any thoughts on when you'll get a new release pushed to nuget?

**Comment by mattosaurus** [comment]
Hi, sorry for the delay. I was adding in some other changes as well and then work picked up again and now I'm back on holiday :)

I'd hope to have something released in the next couple of weeks but am happy to publish earlier and then push out changes after if this would help you now?

**Comment by martinjt** [comment]
Don't want you to ruin your holiday dude... the sooner it's released, the sooner I can delete the copy I have in the code.  Literally just came back to the project I needed it for and wanted to delete the copy in there.

**Comment by bitcoinbrisbane** [comment]
> Removing them as part of a larger interface refactor as part of a V2 would be fine. Major versions, major changes.
> 
> I may give it a go as a new branch in the next few weeks and see what it looks like.

Can we do this as a Github work flow or circle ci process off master branch or something?

**Pull request merged**
