### PR TITLE
DecryptAndVerify fixes

### PR DESCRIPTION
**Pull request by James-Lappin**
Hey, great library btw.

I was trying to use `pgp.DecryptAndVerify()` and was receiving the error `invalid header encountered`. 

I wrote the test to see if it was something I was doing wrong and got the same error.

- Noticed that in other places a decoded stream is passed to ExtractPublicKeyEncryptedData.
- The message is already decrypted in the helper methods.

### CODE REVIEW

**Comment by christiansgithub** [comment]
Hey. This looks like a great fix and potentially fixes an issue I was having with the same "invalid header encountered" error.

Related to this, something else I noticed with the DecryptAndVerify function is that it first checks whether the keys match before the message is decrypted, which seems to mean that only if the message was encrypted and signed by the same sender (with the same private/public pair) will it pass the initial verification check (publicKeyED.KeyId != encryptionKeys.PublicKey.KeyId). I believe this is because it appears to be retrieving the key used to encrypt the message, rather than the one that was used to sign it, but these could differ.

Example:
If I have only one user and they sign a message with their secret key and encrypt it using their public key, they can then decrypt their own message with their secret key and verify it came from them using their public key as the key ids are the same.

However, if there are two users (say client and server) who each have their own secret and public key pairs, if the server signs the key with their secret key and encrypts it with the client's public key, I would expect that the client could decrypt the message using their private key and then verify that the server sent it using the server's public key. However, this does not appear to work with this library as it's seems to try to verify the key used to encrypt is the same as that used to sign, and doing so before decrypting.

I wondered, did you notice anything similar while you were working on this function or have I misunderstood how this should work?

As an example unit test I would expect to pass:

`        [Theory]
        [InlineData(KeyType.Generated)]
        [InlineData(KeyType.Known)]
        [InlineData(KeyType.KnownGpg)]
        public void DecryptFileAndVerify_DecryptSignedAndEncryptedFileDifferentKeys(KeyType keyType)
        {
            // Arrange
            Arrange(keyType);
            PGP pgp = new PGP();

            // Act
            pgp.EncryptFileAndSign(contentFilePath, encryptedContentFilePath, publicKeyFilePath2, privateKeyFilePath1, password1);
            pgp.DecryptFileAndVerify(encryptedContentFilePath, decryptedContentFilePath1, publicKeyFilePath1, privateKeyFilePath2, password2);
            string decryptedContent = File.ReadAllText(decryptedContentFilePath1);

            // Assert
            Assert.True(File.Exists(encryptedContentFilePath));
            Assert.True(File.Exists(decryptedContentFilePath1));
            Assert.Equal(content, decryptedContent.Trim());

            // Teardown
            Teardown();
        }`

This fails with a "Failed to verify file." error.

**Comment by mattosaurus** [comment]
Thanks for this, I hadn't noticed these issues before. I'll have a look at the issue raised by @christiansgithub and accept the PR next week when I get chance unless this issue is urgent.

**Comment by James-Lappin** [comment]
Noticed one of the tests is failing so will look into it this evening. Not urgent, can use the separate methods in the mean time

**Comment by James-Lappin** [comment]
@christiansgithub I've added your test as I think this is a use case that will come up. It was failing and now passes. Check if it works for you.

**Comment by James-Lappin** [comment]
@mattosaurus will you get a chance to look at this soon?

**Comment by mattosaurus** [comment]
Sorry about the delay, I was hoping to wrap this into a couple of other fixes but I've been pretty busy recently so didn't get the chance. I've merged this and have published v1.7.2 to Nuget.

Thanks for your help :)

**Pull request merged**
