### PR TITLE
Added support for encrypting files for/with multiple publickeys

### PR DESCRIPTION
**Pull request by felix-d-git**
It is very useful to pass more than one public key sometimes. 
This can be done now !

### CODE REVIEW

**Comment by felix-d-git** [comment]
Also, I did not see the need to add an additional overload for `EncryptFile`.

**Comment by mattosaurus** [comment]
Thanks for this, I agree it could certainly be useful. However I think an overload of the EncryptFile method may be a better option to ensure that code written against the current version continues to work with your new code. Does that make sense?

**Comment by felix-d-git** [comment]
Yeah, I agree. May I refactor the common code in both of these overloads to own methods ?

**Comment by mattosaurus** [comment]
Thanks for this, I've merged it into the master branch and have published an updated version of the package to NuGet.

**Comment by felix-d-git** [comment]
Awesome!

**Pull request merged**
